### ISSUE TITLE
GELF appender problem

### ISSUE THREAD

**Issue by ticemochka** [nomiddlename/log4js-node#173]
Basically I have this error stacktrace
C:\workspace_frontend\chat-websocket-server\node_modules\log4js\lib\appenders\GELF.js:88
    if (!firstData.GELF) return; // identify with GELF field defined
                  ^
TypeError: Cannot read property 'GELF' of undefined
    at addCustomFields (C:\workspace_frontend\chat-websocket-server\node_modules\log4js\lib\appenders\GELF.js:88:19)
    at preparePacket (C:\workspace_frontend\chat-websocket-server\node_modules\log4js\lib\appenders\GELF.js:102:5)
    at Logger.<anonymous> (C:\workspace_frontend\chat-websocket-server\node_modules\log4js\lib\appenders\GELF.js:121:19)
    at Logger.EventEmitter.emit (events.js:117:20)
    at Logger.log (C:\workspace_frontend\chat-websocket-server\node_modules\log4js\lib\logger.js:54:8)
    at Logger.(anonymous function) [as info](C:workspace_frontendchat-websocket-servernode_moduleslog4jsliblogger.js:72:30)
    at Server.<anonymous> (C:\workspace_frontend\chat-websocket-server\lib\chatServer.js:36:16)
    at Server.g (events.js:175:14)
    at Server.EventEmitter.emit (events.js:117:20)
    at net.js:1052:10

It is happened when the value of logging message is undefined or null. I suppose this is an error.

**Comment by sentient** [comment]
I noticed there are some changes coming up with https://github.com/nomiddlename/log4js-gelf
But I wonder if this issue has been fixed when a null value goes to the gelf appender.

I don't think we can use the log4js-gelf yet beause it requires log4js >= 0.7 

Examining all my log invocations on possible null is some work for just this appender.

**Comment by darky** [comment]
Hey! It's a big trouble, that can destroy your app.

**Comment by sentient** [comment]
I forked the repo and made a small change

https://github.com/sentient/log4js-node/commits/master

**Comment by nomiddlename** [comment]
Fix pushed to NPM in version 2.3.0
