### ISSUE TITLE
How to define token in config json file

### ISSUE THREAD

**Issue by rndmania** [nomiddlename/log4js-node#225]
I want do below using log4js.json

log4js.configure(
{
  appenders: [
    {
       type: "fileSync",  
       filename: 'test.log' + '_' + process.env["LOG_INDEX"],
       pattern: ".yyyy-MM-dd",
       category: "am-log",
       layout: {
          type: "pattern",
          pattern: "%x{utc}|%m",
          tokens: {"utc" : function() { return new Date().toISOString() } }
       }
    }
  ]
}
);

but in json file,
"tokens": {"utc" : function() { return new Date().toISOString() } }  line
parsing error
if modify to
"tokens": {"utc" : "function() { return new Date().toISOString() }" }
utc token convert to string not a function

how to define token in json file?

**Comment by Laessig** [comment]
I have another workaround. It's kind of obvious, but I simply require it as a module.

log4js_conf.js
```javascript
exports = module.exports = { 
   "appenders": [
      {
        "type": "console",
        "layout": {
          "type": "pattern",
          "pattern": "%[%r (%x{pid}) %p %c -%] %m%n",
          "tokens": {
            "pid" : function() { return process.pid; }
          }
        }
      }
    ]
  };
```javascript

**Comment by nomiddlename** [comment]
Closing this for a few reasons - config reloading is no longer supported, and there is a workaround available by using object configuration.

**Comment by 200688523** [comment]
When using the file loading method of the configure method, an error is reported.
```typescript
import { getLogger, configure, Logger } from 'log4js';

configure('log4js-config.json')
const logger:Logger = getLogger();

export {logger};
```

**error:**
return JSON.parse(fs.readFileSync(filename, 'utf8'));
                ^
SyntaxError: Unexpected token o in JSON at position 224
    at JSON.parse (<anonymous>)
    at loadConfigurationFile (E:\002_jsproject\002_microservice\nest_shop\packages\ns-systems\node_modules\log4js\lib\log4js.js:49:17)
    at Object.configure (E:\002_jsproject\002_microservice\nest_shop\packages\ns-systems\node_modules\log4js\lib\log4js.js:58:20)
    at Object.<anonymous> (E:\002_jsproject\002_microservice\nest_shop\packages\ns-systems\src\logger\logger.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Module.m._compile (E:\002_jsproject\002_microservice\nest_shop\packages\ns-systems\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Object.require.extensions.(anonymous function) [as .ts] (E:\002_jsproject\002_microservice\nest_shop\packages\ns-systems\node_modules\ts-node\src\index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)

**Comment by nomiddlename** [comment]
I don't think JSON supports octal literals like Javascript does.

**Comment by 200688523** [comment]
> I don't think JSON supports octal literals like Javascript does.

Thank you, the problem has been solved
