### ISSUE TITLE
console.trace throws errors. Why ?

### ISSUE THREAD

**Issue by SimoneTaliercio** [nomiddlename/log4js-node#273]
Hi,

first of all thanks for this awesome 'porting' of log4j.

I'm facing with an issue when using console.trace("a message") in my code. It produces the following stacktrace:
```
[2015-01-30 09:59:12.002] [ERROR] console - Trace: a message
    at Object.create (/path/to/my/file/script.js:485:10)
    at createOrExtend (/path/to/my/file/script.js:126:43)
    at /path/to/my/file/script.js:211:30
    at notify (/path/to/my/project/node_modules/promised-io/promise.js:201:22)
    at notifyAll ((/path/to/my/project/node_modules/promised-io/promise.js:180:5)
    at Deferred.resolve.callback.emitSuccess ((/path/to/my/project/node_modules/promised-io/promise.js:223:3)
    at /path/to/my/file/script2.js:168:11
    at notify (/path/to/my/project/node_modules/promised-io/promise.js:201:22)
    at notifyAll (/path/to/my/project/node_modules/promised-io/promise.js:180:5)
    at Deferred.resolve.callback.emitSuccess (/path/to/my/project/node_modules/promised-io/promise.js:223:3)
```

Note: I needed to replace some path because confidential info.

This is my settings:
```
var log4js = require('log4js');

var config = {

	appenders : [ {
		type : "console"
	} ],
	
	replaceConsole : true,
	
	levels : {
		"[all]" : "DEBUG"
	}

};

log4js.configure(config, {});
```
What am I doing wrong? :-/

Thanks for any help!

**Comment by nomiddlename** [comment]
I think what is happening is that log4js does not replace node's `console.trace` function - and the original function, according to the [docs](http://nodejs.org/api/console.html#console_console_trace_message), prints a stack trace. My guess is that it actually throws an exception, and log4js's default uncaught exception handler prints it out as an error. Does that help?

**Comment by SimoneTaliercio** [comment]
Thanks a lot for the help @nomiddlename 
I'll try asap to isolate that code in a separate 'hello-world' project and see if i get the same trouble :)

Stay tuned!

**Comment by SimoneTaliercio** [comment]
And here my 2-cents: you are right! :)
```
var log4js = require('log4js');

var config = {

	appenders : [ {
		type : "console"
	} ],
	
	replaceConsole : true,
	
	levels : {
		"[all]" : "TRACE"
	}

};

log4js.configure(config, {});
var logger = log4js.getLogger();

console['trace'] = function(str){
	logger.trace(str);
}

console.trace("This is a test!");
```
