### ISSUE TITLE
Problem with Q

### ISSUE THREAD

**Issue by TitForTat** [nomiddlename/log4js-node#299]
Hi. Why is it that this works:

    Q('a').done(onDone);
  
    function onDone(msg) {
      logger.info(msg);
    }

but this

    Q('a').done(logger.info);

throws this

    TypeError: Cannot call method 'isLevelEnabled' of undefined
        at Logger.(anonymous function) (/Users/../node_modules/log4js/lib/logger.js:74:36)
        at _fulfilled (/Users/../node_modules/q/q.js:794:54)
        at self.promiseDispatch.done (/Users/../node_modules/q/q.js:823:30)
        at Promise.promise.promiseDispatch (/Users/../node_modules/q/q.js:756:13)
        at /Users/../node_modules/q/q.js:817:14
        at flush (/Users/../node_modules/q/q.js:110:17)
        at process._tickCallback (node.js:442:13)
        at Function.Module.runMain (module.js:499:11)
        at startup (node.js:119:16)
        at node.js:929:3

? Is there any easy fix for it?

**Comment by nomiddlename** [comment]
Yep, you need to bind the function call to the instance. Try `Q('a').done(logger.info.bind(logger))`

**Comment by TitForTat** [comment]
hey thanks! :+1:
