### ISSUE TITLE
Console can throw unhandled errors

### ISSUE THREAD

**Issue by jrust** [nomiddlename/log4js-node#324]
I've seen this a number of times on OSX, but very intermittently, when logging to console errors out with the following exception:

```
throw er; // Unhandled 'error' event

Error: This socket is closed.
    at Socket._writeGeneric (net.js:656:19)
    at Socket._write (net.js:709:8)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Socket.Writable.write (_stream_writable.js:217:11)
    at Socket.write (net.js:634:40)
    at Console.log (console.js:55:16)
    at Array.<anonymous> (./node_modules/log4js/lib/appenders/console.js:8:5)
    at Logger.masterAppender (./node_modules/log4js/lib/appenders/clustered.js:76:32)
    at Logger.emit (events.js:107:17)
```

Usually seems to happen after putting the machine to sleep.  Would it be reasonable to wrap the console appender statement in a try/catch?  Or is there a better way to prevent it from being an unhandled event?

**Comment by nomiddlename** [comment]
There's been a lot of changes since this was first raised - if this is still happening feel free to re-open.
