### ISSUE TITLE
CTRL-C causes error writing to log file

### ISSUE THREAD

**Issue by eharrow** [nomiddlename/log4js-node#374]
I have a file appender that works fine when the app is running but on a ctrl-c it bombs out spectacularly with the underlying cause being `RangeError: Maximum call stack size exceeded` and the log file does have entries written successfully upto this point:

**version**

```
[vagrant@localhost app]$ npm list log4js
pushnotify-server@1.0.0-SNAPSHOT /opt/company/pushnotify-server/app
└── log4js@0.6.35 
```

**log4js config**

```
{
  "appenders": [
    {
      "type": "logLevelFilter",
      "level": "WARN",
      "appender": {
        "type": "console"
      }
    },
    {
      "type": "logLevelFilter",
      "level": "ALL",
      "appender": {
        "type": "file",
        "filename": "/tmp/WebMQProducer.log",
        "layout": {
          "type": "pattern",
          "pattern": "%d|%z|[%5p]|%c{3} - %m"
        }
      }
    }
  ],
  "replaceConsole": true
}
```

**Trace**

```
[2016-04-18 11:14:18.664] [INFO] console - debug: acknowledged message: mybroker-782
^C[2016-04-18 11:14:21.241] [ERROR] console - log4js.fileAppender - Writing to file /tmp/WebMQProducer.log, error happened  [Error: write after end]
Error: write after end
    at writeAfterEnd (_stream_writable.js:167:12)
    at WriteStream.Writable.write (_stream_writable.js:212:5)
    at /opt/company/pushnotify-server/app/node_modules/log4js/lib/appenders/file.js:68:13
    at Logger.<anonymous> (/opt/company/pushnotify-server/app/node_modules/log4js/lib/appenders/logLevelFilter.js:11:7)
    at emitOne (events.js:95:20)
    at Logger.emit (events.js:182:7)
    at Logger._log (/opt/company/pushnotify-server/app/node_modules/log4js/lib/logger.js:91:8)
    at Logger.(anonymous function) [as info] (/opt/company/pushnotify-server/app/node_modules/log4js/lib/logger.js:83:14)
    at process.<anonymous> (/vagrant/test/VIPWebMQProducer.js:510:10)
    at emitOne (events.js:95:20)
[2016-04-18 11:14:21.246] [ERROR] console - log4js.fileAppender - Writing to file /tmp/WebMQProducer.log, error happened  [Error: write after end]
Error: write after end
    at writeAfterEnd (_stream_writable.js:167:12)
    at WriteStream.Writable.write (_stream_writable.js:212:5)
    at /opt/company/pushnotify-server/app/node_modules/log4js/lib/appenders/file.js:68:13
    at Logger.<anonymous> (/opt/company/pushnotify-server/app/node_modules/log4js/lib/appenders/logLevelFilter.js:11:7)
    at emitOne (events.js:95:20)
    at Logger.emit (events.js:182:7)
    at Logger._log (/opt/company/pushnotify-server/app/node_modules/log4js/lib/logger.js:91:8)
    at Logger.(anonymous function) [as error] (/opt/company/pushnotify-server/app/node_modules/log4js/lib/logger.js:83:14)
    at Console.error (/opt/company/pushnotify-server/app/node_modules/log4js/lib/log4js.js:359:10)
    at WriteStream.<anonymous> (/opt/company/pushnotify-server/app/node_modules/log4js/lib/appenders/file.js:57:15)
[2016-04-18 11:14:21.247] [ERROR] console - log4js.fileAppender - Writing to file /tmp/WebMQProducer.log, error happened  [Error: write after end]
Error: write after end
    at writeAfterEnd (_stream_writable.js:167:12)
    at WriteStream.Writable.write (_stream_writable.js:212:5)
    at /opt/company/pushnotify-server/app/node_modules/log4js/lib/appenders/file.js:68:13
    at Logger.<anonymous> (/opt/company/pushnotify-server/app/node_modules/log4js/lib/appenders/logLevelFilter.js:11:7)
    at emitOne (events.js:95:20)
    at Logger.emit (events.js:182:7)
    at Logger._log (/opt/company/pushnotify-server/app/node_modules/log4js/lib/logger.js:91:8)
    at Logger.(anonymous function) [as error] (/opt/company/pushnotify-server/app/node_modules/log4js/lib/logger.js:83:14)
    at Console.error (/opt/company/pushnotify-server/app/node_modules/log4js/lib/log4js.js:359:10)
    at WriteStream.<anonymous> (/opt/company/pushnotify-server/app/node_modules/log4js/lib/appenders/file.js:57:15)
[2016-04-18 11:14:21.247] [ERROR] console - log4js.fileAppender - Writing to file /tmp/WebMQProducer.log, error happened  [Error: write after end]
Error: write after end
    at writeAfterEnd (_stream_writable.js:167:12)
    at WriteStream.Writable.write (_stream_writable.js:212:5)
    at /opt/company/pushnotify-server/app/node_modules/log4js/lib/appenders/file.js:68:13
    at Logger.<anonymous> (/opt/company/pushnotify-server/app/node_modules/log4js/lib/appenders/logLevelFilter.js:11:7)
    at emitOne (events.js:95:20)
    at Logger.emit (events.js:182:7)
    at Logger._log (/opt/company/pushnotify-server/app/node_modules/log4js/lib/logger.js:91:8)
    at Logger.(anonymous function) [as error] (/opt/company/pushnotify-server/app/node_modules/log4js/lib/logger.js:83:14)
    at Console.error (/opt/company/pushnotify-server/app/node_modules/log4js/lib/log4js.js:359:10)
    at WriteStream.<anonymous> (/opt/company/pushnotify-server/app/node_modules/log4js/lib/appenders/file.js:57:15)
[2016-04-18 11:14:21.247] [ERROR] console - log4js.fileAppender - Writing to file /tmp/WebMQProducer.log, error happened  [Error: write after end]
Error: write after end
    at writeAfterEnd (_stream_writable.js:167:12)
    at WriteStream.Writable.write (_stream_writable.js:212:5)
    at /opt/company/pushnotify-server/app/node_modules/log4js/lib/appenders/file.js:68:13
    at Logger.<anonymous> (/opt/company/pushnotify-server/app/node_modules/log4js/lib/appenders/logLevelFilter.js:11:7)
    at emitOne (events.js:95:20)
    at Logger.emit (events.js:182:7)
    at Logger._log (/opt/company/pushnotify-server/app/node_modules/log4js/lib/logger.js:91:8)
    at Logger.(anonymous function) [as error] (/opt/company/pushnotify-server/app/node_modules/log4js/lib/logger.js:83:14)
    at Console.error (/opt/company/pushnotify-server/app/node_modules/log4js/lib/log4js.js:359:10)
    at WriteStream.<anonymous> (/opt/company/pushnotify-server/app/node_modules/log4js/lib/appenders/file.js:57:15)
[2016-04-18 11:14:21.248] [ERROR] console - log4js.fileAppender - Writing to file /tmp/WebMQProducer.log, error happened  [Error: write after end]
Error: write after end
    at writeAfterEnd (_stream_writable.js:167:12)
    at WriteStream.Writable.write (_stream_writable.js:212:5)
    at /opt/company/pushnotify-server/app/node_modules/log4js/lib/appenders/file.js:68:13
    at Logger.<anonymous> (/opt/company/pushnotify-server/app/node_modules/log4js/lib/appenders/logLevelFilter.js:11:7)
    at emitOne (events.js:95:20)
    at Logger.emit (events.js:182:7)
    at Logger._log (/opt/company/pushnotify-server/app/node_modules/log4js/lib/logger.js:91:8)
    at Logger.(anonymous function) [as error] (/opt/company/pushnotify-server/app/node_modules/log4js/lib/logger.js:83:14)
    at Console.error (/opt/company/pushnotify-server/app/node_modules/log4js/lib/log4js.js:359:10)
    at WriteStream.<anonymous> (/opt/company/pushnotify-server/app/node_modules/log4js/lib/appenders/file.js:57:15)
[2016-04-18 11:14:21.248] [ERROR] console - log4js.fileAppender - Writing to file /tmp/WebMQProducer.log, error happened  [Error: write after end]
Error: write after end
    at writeAfterEnd (_stream_writable.js:167:12)
    at WriteStream.Writable.write (_stream_writable.js:212:5)
    at /opt/company/pushnotify-server/app/node_modules/log4js/lib/appenders/file.js:68:13
    at Logger.<anonymous> (/opt/company/pushnotify-server/app/node_modules/log4js/lib/appenders/logLevelFilter.js:11:7)
    at emitOne (events.js:95:20)
    at Logger.emit (events.js:182:7)
    at Logger._log (/opt/company/pushnotify-server/app/node_modules/log4js/lib/logger.js:91:8)
    at Logger.(anonymous function) [as error] (/opt/company/pushnotify-server/app/node_modules/log4js/lib/logger.js:83:14)
    at Console.error (/opt/company/pushnotify-server/app/node_modules/log4js/lib/log4js.js:359:10)
    at WriteStream.<anonymous> (/opt/company/pushnotify-server/app/node_modules/log4js/lib/appenders/file.js:57:15)
[2016-04-18 11:14:21.248] [ERROR] console - log4js.fileAppender - Writing to file /tmp/VIPWebMQProducer.log, error happened  [Error: write after end]util.js:452
function formatPrimitive(cox, value) {
                        ^

RangeError: Maximum call stack size exceeded
    at formatPrimitive (util.js:452:25)
    at formatValue (util.js:261:19)
    at inspect (util.js:143:10)
    at Object.exports.format (util.js:24:24)
    at Object.inspect (/opt/company/pushnotify-server/app/node_modules/log4js/lib/layouts.js:31:50)
    at formatValue (util.js:253:21)
    at inspect (util.js:143:10)
    at Object.exports.format (util.js:82:20)
    at formatLogData (/opt/company/pushnotify-server/app/node_modules/log4js/lib/layouts.js:40:22)
    at colouredLayout (/opt/company/pushnotify-server/app/node_modules/log4js/lib/layouts.js:110:7)
    at /opt/company/pushnotify-server/app/node_modules/log4js/lib/appenders/console.js:8:16
```

**Comment by eharrow** [comment]
I think I have found a solution which is to call `log4js.shutdown()` in your process SIGINT handler

```
process.on('SIGINT', function() {
    log4js.shutdown();
    client.disconnect();
});
```

It would be worth updating the docs to reflect this.  Many thanks.

**Comment by lsicotteSinope** [comment]
Had the same situation and scratched my head for way too long before finding your post.
Thanks for your solution, worked great !
And, yes, the log4js docs need a serious update !

**Comment by nomiddlename** [comment]
Docs have been updated for version 2.x :)
