### ISSUE TITLE
Error:Cannot find module 'file'

### ISSUE THREAD

**Issue by farell** [nomiddlename/log4js-node#386]
running the example log-rolling.js get the following error:

H:\opc\service\node_modules\log4js\lib\log4js.js:290
      throw new Error(
      ^

Error: Problem reading log4js config { appenders:
   [ { type: 'console', category: 'console', makers: [Object] },
     { type: 'file',
       filename: 'tmp-test.log',
       maxLogSize: 1024,
       backups: 3,
       category: 'test' } ] }. Error was "Cannot find module 'file'" (Error: Can
not find module 'file'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at requireAppender (H:\opc\service\node_modules\log4js\lib\log4js.js:388:22)

```
at loadAppender (H:\opc\service\node_modules\log4js\lib\log4js.js:404:38)
at H:\opc\service\node_modules\log4js\lib\log4js.js:225:7
at Array.forEach (native)
at configureAppenders (H:\opc\service\node_modules\log4js\lib\log4js.js:224:
```

18)
    at configureOnceOff (H:\opc\service\node_modules\log4js\lib\log4js.js:282:7)
)
    at configureOnceOff (H:\opc\service\node_modules\log4js\lib\log4js.js:290:13
)
    at Object.configure (H:\opc\service\node_modules\log4js\lib\log4js.js:345:3)

```
at Object.<anonymous> (H:\opc\service\acquisition\fetching.js:48:8)
at Module._compile (module.js:399:26)
at Object.Module._extensions..js (module.js:406:10)
at Module.load (module.js:345:32)
at Function.Module._load (module.js:302:12)
at Function.Module.runMain (module.js:431:10)
at startup (node.js:141:18)
at node.js:977:3
```

**Comment by songlong** [comment]
the same problem..............

**Comment by nomiddlename** [comment]
I haven't been able to reproduce this problem. If this is still occurring, please re-open the issue.
