### ISSUE TITLE
TypeError: connectLogger is not a function (undefined)

### ISSUE THREAD

**Issue by chan337337** [nomiddlename/log4js-node#499]
Running `example-connect-logger.js` from HEAD:
```
TypeError: log4js.connectLogger is not a function
    at Object.<anonymous> (.../examples/example-connect-logger.js:36:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

Calling `log4js.configure()` doesn't change connectLogger.
How can I use connectLogger? 

When I use connectModule directly, it works fine.
Is this right usage?
```
const connectModule = require('log4js/lib/connect-logger.js');
...
app.use(connectModule(log4js.levels).connectLogger(logger, { level: 'auto' }));
```

**Comment by nomiddlename** [comment]
Sorry about that - I've just pushed v2.0.1 to NPM which should fix this problem.

**Comment by chan337337** [comment]
@nomiddlename Thank you. It works at v2.0.1!
