### ISSUE TITLE
log4js how to close the file

### ISSUE THREAD

**Issue by acekingke** [nomiddlename/log4js-node#540]
After I configure the appenders ，I found the log4js open the log file ,but nerver close the file, When I configure another ,It open a new file ,but the old file donot close, how to close them ?

**Comment by nomiddlename** [comment]
It will close the files when you call `log4js.shutdown`.

**Comment by acekingke** [comment]
but I use shutdown ， It cause error as follow
```
write after end
    at writeAfterEnd (XXXXXXXXXXXX\node_modules\log4js\node_modules\readable-stream\lib\_stream_writable.js:276:12)
    at DateRollingFileStream.Writable.write (D:\work\mahjong-backend\node_modules\log4js\node_modules\readable-stream\lib\_stream_writable.js:320:20)
    at XXXXXXXXXXXX\node_modules\log4js\lib\appenders\dateFile.js:78:15
    at Array.forEach (native)
    at Object.shutdown (XXXXXXXXXXXX\node_modules\log4js\lib\appenders\dateFile.js:77:13)
````

**Comment by acekingke** [comment]
I have modify the log4js code, now resolve the problem
