### ISSUE TITLE
TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by jokyme** [nomiddlename/log4js-node#549]
i packaged my node project as a windows application by using nexe,
and when i try to run the application, the log4js throw an exception as blow.

path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.dirname (path.js:716:5)
    at Configuration.loadAppenderModule (C:\Source_Code\crawler-node\crawler.exe:14187:38)
    at Configuration.createAppender (C:\Source_Code\crawler-node\crawler.exe:14192:33)
    at appenderNames.forEach (C:\Source_Code\crawler-node\crawler.exe:14235:47)
    at Array.forEach (<anonymous>)
    at Configuration.set appenders [as appenders] (C:\Source_Code\crawler-node\crawler.exe:14228:19)
    at new Configuration (C:\Source_Code\crawler-node\crawler.exe:14331:20)
    at configure (C:\Source_Code\crawler-node\crawler.exe:14041:12)
    at Number.<anonymous> (C:\Source_Code\crawler-node\crawler.exe:14121:1)

log4js configuration:

```
const log4js = require("log4js");

let log = () => {
    try{
        log4js.configure({
            appenders: {
                out: {type: 'stdout'},
                app: { type: 'file', filename: 'crawler.log'}
            },
            categories: {
                default: {appenders: ['out', 'app'], level: 'info'}
            }
        });
        return log4js.getLogger();
    }catch(e){
        console.error(e);
    }
};

module.exports = log;
```

**Comment by cula** [comment]
See [https://github.com/nexe/nexe/issues/378](url)   [https://github.com/nexe/nexe/issues/344](url)
Please try:
`
require('log4js/lib/appenders/stdout')
require('log4js/lib/appenders/file')
`
If this does not work, please tell the version of log4js and nexe.

**Comment by nomiddlename** [comment]
Thanks @cula (I edited your comment - the links weren't working for some reason). 

This looks to be a similar problem to browserify-type things - log4js loads appenders dynamically using `require` during configuration, so tools like this have a hard time identifying which modules to bundle up.

**Comment by jokyme** [comment]
@cula  Thanks, it's work for me

```JavaScript
require('log4js/lib/appenders/stdout');
require('log4js/lib/appenders/file');
const log4js = require("log4js");
```
