### ISSUE TITLE
Error: Problem with log4js configuration

### ISSUE THREAD

**Issue by andrei16123** [nomiddlename/log4js-node#555]
So I am really new to linux, I was trying to execute a script and I got this error... , I am using debian 7.11 x 64 on a vps. Can anyone help me? I would really apreciate it! :)

root@Test:/home/bot# node site.js
/home/bot/node_modules/log4js/lib/configuration.js:44
        throw new Error(
        ^

Error: Problem with log4js configuration: ({ appenders:
   [ { type: 'console' },
     { type: 'file', filename: 'logs/site.log' } ] }) - must have a property "appenders" of type object.
    at tests.forEach (/home/bot/node_modules/log4js/lib/configuration.js:44:15)
    at Array.forEach (native)
    at Configuration.throwExceptionIf (/home/bot/node_modules/log4js/lib/configuration.js:42:11)
    at new Configuration (/home/bot/node_modules/log4js/lib/configuration.js:205:10)
    at Object.configure (/home/bot/node_modules/log4js/lib/log4js.js:201:12)
    at Object.<anonymous> (/home/bot/site.js:10:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

**Comment by nomiddlename** [comment]
Looks like you're trying to use log4js 1.x style configuration with log4js version 2.x. Your config above needs to be something like this:
```javascript
log4js.configure({
  appenders: {
    'console': { type: 'stdout' },
    'file': { type: 'file', filename: 'logs/site.log' }
  },
  categories: {
    default: { appenders: [ 'console','file' ], level: 'debug' }
  }
});
```
Note that generally, it's better to use the stdout appender instead of the console appender (better memory performance).

**Comment by nomiddlename** [comment]
I'm going to assume that this fixed your problem. Feel free to re-open this issue if it didn't. Thanks.
