### ISSUE TITLE
log4js error!

### ISSUE THREAD

**Issue by MagicalAppleMan** [nomiddlename/log4js-node#558]
I have researched this and nothing has helped,

Please help me!

root@csgo-gambel:/home/bot# node site.js
/home/bot/node_modules/log4js/lib/configuration.js:44
        throw new Error(
        ^

Error: Problem with log4js configuration: ({ appenders:
   [ { type: 'console' },
     { type: 'file', filename: 'logs/site.log' } ] }) - must have a property "ap         penders" of type object.
    at tests.forEach (/home/bot/node_modules/log4js/lib/configuration.js:44:15)
    at Array.forEach (<anonymous>)
    at Configuration.throwExceptionIf (/home/bot/node_modules/log4js/lib/configu         ration.js:42:11)
    at new Configuration (/home/bot/node_modules/log4js/lib/configuration.js:205         :10)
    at Object.configure (/home/bot/node_modules/log4js/lib/log4js.js:201:12)
    at Object.<anonymous> (/home/bot/site.js:36:8)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
root@csgo-gambel:/home/bot#

**Comment by victor0801x** [comment]
It seems you are using 1.x configure on log4js 2.x.
you can see the migration guide  https://nomiddlename.github.io/log4js-node/migration-guide.html

**Comment by MagicalAppleMan** [comment]
Not working ill upload the files

[files.zip](https://github.com/nomiddlename/log4js-node/files/1360805/files.zip)

**Comment by nomiddlename** [comment]
Hi @MagicalAppleMan - did you try changing your configuration like @victor0801x mentioned? Did you get a different error?

Don't take this the wrong way, but I'm not going to open a zip file of unknown code to find your error for you. If you want people to look at your code, either put it in a gist (github makes this very easy) or a repo that we can access. Gist is probably easiest.

**Comment by MagicalAppleMan** [comment]
Thanks @nomiddlename, 
Ill try that and thanks for the speedy reply,


Thanks,


Niko

**Comment by nomiddlename** [comment]
I'm going to assume that this fixed your problem, so I'm closing this issue. Feel free to re-open if it did not.
