### ISSUE TITLE
Log4js error code won't start.

### ISSUE THREAD

**Issue by KnottyCord** [nomiddlename/log4js-node#563]
When I try to lunch my application I get this error.

```
/var/www/html/Bot/node_modules/log4js/lib/configuration.js:44
        throw new Error(
        ^

Error: Problem with log4js configuration: ({ appenders:
   [ { type: 'console' },
     { type: 'file', filename: 'logs/site_1507601930.log' } ] }) - must have a property "appenders" of type object.
    at tests.forEach (/var/www/html/Bot/node_modules/log4js/lib/configuration.js:44:15)
    at Array.forEach (<anonymous>)
    at Configuration.throwExceptionIf (/var/www/html/Bot/node_modules/log4js/lib/configuration.js:42:11)
    at new Configuration (/var/www/html/Bot/node_modules/log4js/lib/configuration.js:205:10)
    at Object.configure (/var/www/html/Bot/node_modules/log4js/lib/log4js.js:201:12)
    at updateLog (/var/www/html/Bot/cf.js:31:9)
    at Object.<anonymous> (/var/www/html/Bot/cf.js:29:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
```

**Comment by nomiddlename** [comment]
You're using log4js v1.x configuration with logj4s v2.x. Take a look at the docs to see what you need to do. But it sort of looks like this:
```javascript
log4js.configure({
  appenders: { 
    console: { type: 'console' },
    file: { type: 'file', filename: 'logs/sdfsdfsdf.log' }
  },
  categories: { default: { appenders: ['file','console' ], level: 'debug' }
});
```
