### ISSUE TITLE
Error loading dateFile appender

### ISSUE THREAD

**Issue by blevine** [nomiddlename/log4js-node#96]
I've been unable to configure log4js using the 'dateFile' appender. I am using the following config (loaded from a log4j.json file) to configure a logger that I pass to Express. I can use a 'file' appender without any problem.

{
    "appenders":[
        {"type":"console", "category": "Query"},
        {"type":"console", "category": "ORM"},
        {"type":"dateFile", "filename": "foo", "pattern":"-yyyy-MM-dd", "category":"access" }
    ],
    "replaceConsole":false,

    "levels": {
        "ORM": "DEBUG",
        "Query":  "DEBUG",
        "access": "INFO"
    }
}

Error is:

Error: Problem reading log4js config { appenders: 
   [ { type: 'console', category: 'Query', makers: [Object] },
     { type: 'console', category: 'ORM', makers: [Object] },
     { type: 'dateFile', filename: 'foo', pattern: '-yyyy-MM-dd' } ],
  replaceConsole: false,
  levels: { ORM: 'DEBUG', Query: 'DEBUG', access: 'INFO' } }. Error was "Cannot find module 'dateFile'" (Error: Cannot find module 'dateFile'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at loadAppender (/home/blevine/work/ultra.orm/node_modules/log4js/lib/log4js.js:289:26)
    at /home/blevine/work/ultra.orm/node_modules/log4js/lib/log4js.js:145:13
    at Array.forEach (native)
    at configureAppenders (/home/blevine/work/ultra.orm/node_modules/log4js/lib/log4js.js:144:22)
    at configureOnceOff (/home/blevine/work/ultra.orm/node_modules/log4js/lib/log4js.js:196:13)
    at Object.configure (/home/blevine/work/ultra.orm/node_modules/log4js/lib/log4js.js:255:5))
    at configureOnceOff (/home/blevine/work/ultra.orm/node_modules/log4js/lib/log4js.js:205:19)
    at Object.configure (/home/blevine/work/ultra.orm/node_modules/log4js/lib/log4js.js:255:5)
    at Object.exports.getLogger (/home/blevine/work/ultra.orm/lib/utils.js:82:12)
    at Object.<anonymous> (/home/blevine/work/ultra.orm/lib/node.js:12:23)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)

**Comment by nomiddlename** [comment]
Closing this one as a case-sensitive file system problem.
